### ISSUE TITLE
运行的时候报错

### ISSUE THREAD

**Issue by Chaunjie** [stoneWeb/elm-react-native#5]
![image](https://cloud.githubusercontent.com/assets/12093709/22624314/1603da02-ebb3-11e6-8879-d84cfffb639e.png)
@stoneWeb

**Comment by stoneWeb** [comment]
你可以尝试升级下版本， 看这个： https://github.com/stoneWeb/elm-react-native/issues/2
`react-native upgrade`

**Comment by Chaunjie** [comment]
好的，谢谢

**Comment by Chaunjie** [comment]
升级了RN貌似还是报这个错误@stoneWeb

**Comment by stoneWeb** [comment]
尝试重新clone 项目，`npm start -- --reset-cache`，再run。
你看下这个issues里面提到的，和你问题一样：https://github.com/facebook/react-native/issues/7308#issuecomment-267643715
实在不行看看这个 https://github.com/facebook/react-native/issues/7308#issuecomment-218996955 😝😄

**Comment by Chaunjie** [comment]
好的，谢谢

**Comment by dey-dey** [comment]
也有这个运行的时候报错，升级下版本以后，fixed it
