### ISSUE TITLE
请问 readme 的Screenshot 是怎么做出来的？用什么软件？

### ISSUE THREAD

**Issue by xianjingfeng** [stoneWeb/elm-react-native#8]
请问 readme 的Screenshot 是怎么做出来的？用什么软件？ gif的

**Comment by stoneWeb** [comment]
😰  issues 是提BUG的地方
markdown 做的

**Comment by xianjingfeng** [comment]
sorry，因为我特别想知道。我的意思是那个动态图是怎么生成的，gif那个 :smile:

**Comment by stoneWeb** [comment]
电脑运行模拟器，然后录屏，保存成gif

**Comment by xianjingfeng** [comment]
ok,谢谢 :smile:
