### ISSUE TITLE
一直停留在开机启动页

### ISSUE THREAD

**Issue by csgsky** [stoneWeb/elm-react-native#9]
安装，打开，一会停留在开机启动页，进不去

**Comment by csgsky** [comment]
oppo 手机

**Comment by GitZhouQi** [comment]
我也是，卡在启动页

**Comment by Paidaxi** [comment]
我也是 一直停在启动页

**Comment by zhuchaoming** [comment]
悬浮窗权限开了吗？

**Comment by bingshen2016** [comment]
找到MainApplication.java(android/app/src/main/java/com)，里面有有重复的引用，把重复的部分删除就行了

**Comment by ScottYang36** [comment]
在ios simulator 中也是卡在启动页

**Comment by jackhanm** [comment]
卡在启动页，iOS模拟器

**Comment by Versus2017** [comment]
Any solutions?

**Comment by 329463417** [comment]
都怎么解决的啊

**Comment by Versus2017** [comment]
一般这种情况都是因为 启动时，代码出错了导致app 无法正常启动，在启动时，检查一下代码初始化，我的错误时因为初始化极光推送时 错误，导致一直卡在 启动中，而且此时并不会显示任何错误，所以很难发现是什么错误
